"""empty message

Revision ID: 08f355f0314d
Revises: 
Create Date: 2024-02-05 13:25:46.539649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08f355f0314d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monthly_income', sa.Float(), nullable=False),
    sa.Column('savings', sa.Float(), nullable=False),
    sa.Column('bills', sa.Float(), nullable=False),
    sa.Column('entertainment', sa.Float(), nullable=False),
    sa.Column('food', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_table')
    # ### end Alembic commands ###
