"""empty message

Revision ID: 77786c956eaf
Revises: 08f355f0314d
Create Date: 2024-02-05 14:56:53.237893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77786c956eaf'
down_revision = '08f355f0314d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('expense_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plan_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('plan_table', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'plan_table', 'user_table', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plan_table', type_='foreignkey')
    op.drop_column('plan_table', 'user_id')
    op.drop_table('expense_table')
    op.drop_table('user_table')
    # ### end Alembic commands ###
