"""empty message

Revision ID: eb1bd24ad5b1
Revises: 3d43c06acfc4
Create Date: 2024-02-08 14:33:30.936575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb1bd24ad5b1'
down_revision = '3d43c06acfc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('email', sa.String(), nullable=False))
    op.add_column('user_table', sa.Column('password', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'user_table', ['email'])
    op.create_unique_constraint(None, 'user_table', ['password'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_table', type_='unique')
    op.drop_constraint(None, 'user_table', type_='unique')
    op.drop_column('user_table', 'password')
    op.drop_column('user_table', 'email')
    # ### end Alembic commands ###
